version: '2'

services:

    posts:
        image: clue/json-server
        volumes:
            - ./posts.db.json:/data/db.json
        networks:
            - turbosonic_net

    comments:
        image: clue/json-server
        volumes:
            - ./comments.db.json:/data/db.json
        networks:
            - turbosonic_net
    
    profiles:
        image: clue/json-server
        volumes:
            - ./profiles.db.json:/data/db.json
        networks:
            - turbosonic_net
    
    news:
        image: clue/json-server
        volumes:
            - ./news.db.json:/data/db.json
        networks:
            - turbosonic_net
    
    notifications:
        image: clue/json-server
        volumes:
            - ./notifications.db.json:/data/db.json
        networks:
            - turbosonic_net
    
    search:
        image: clue/json-server
        volumes:
            - ./search.db.json:/data/db.json
        networks:
            - turbosonic_net

    gateway:
        image: turbosonic/api-gateway
        ports: 
            - 80:80
        volumes:
            - ./gateway.config.yaml:/data/config.yaml
        environment:
          AUTHENTICATION_PROVIDER: none
        networks:
            - turbosonic_net




networks:
  turbosonic_net:
